# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/dinesh_repo
    steps:
      - checkout
      - restore_cache:
        key: ~/dinesh_repo-{{ checksum "pom.xml" }}
      run: mvn dependency:go-offline
      - save_cache:
        paths:
          - ~/.m2
        key: ~/dinesh_repo-{{ checksum "pom.xml" }}
      - run: mvn compile test
      - store_test_results:
        path: target/surefire-reports
